#! /usr/bin/env bash

function show_help () {
	echo "Usage: docker-cli [comand]"
	echo "	command: build, run, attach, stop"
    echo "  help: -h, --help"
}

cmd=$1

if [ "$cmd" == "-h" ] || [ "$cmd" == "--help" ];
then
	show_help
elif [ "$cmd" == "build" ];
then
	docker build -t "${PWD##*/}" .
elif [ "$cmd" == "run" ];
then
    docker run -dit --rm --name "${PWD##*/}-1" -p 443:443 -p 80:80 -v /var/log:/var/log -v "$PWD":/var/www/html/ "${PWD##*/}"
elif [ "$cmd" == "attach" ];
then
    docker exec -it "${PWD##*/}-1" bash
elif [ "$cmd" == "stop" ];
then
    docker stop "${PWD##*/}-1"
else
	echo "ERROR: Unknown action $cmd"
	show_help
fi
